spring.application.name=fintrackautentication

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

spring.datasource.url=jdbc:postgresql://localhost:5432/FintrackAutenticacion
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.flyway.baselineOnMigrate=true

jwt.secret=YzJmZjYyZjM0ZTRjYzQ1ZmE2OTc4YWJjZGVmMTIzNDU2Nzg5MDEyMzQ1Ng==
# JWT expirations (milliseconds)
# 15 minutes
jwt.access.expiration-ms=900000
# 7 days
jwt.refresh.expiration-ms=604800000

# Seguridad - maximos intentos fallidos antes de bloquear la cuenta
security.max-intentos-fallidos=5

# Puerto del microservicio (diferente a 8080)
server.port=8083
