spring.application.name=fintrackautentication

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# # Debug logging to diagnose /v3/api-docs 403
# logging.level.org.springframework.security=DEBUG
# logging.level.org.springdoc=DEBUG

# # Expose actuator mappings + beans for debugging
# management.endpoints.web.exposure.include=mappings,health,info,beans
# # Enable springdoc OpenAPI generation and Swagger UI
# springdoc.api-docs.enabled=true
# springdoc.swagger-ui.enabled=true

# Hibernate DDL auto (create/update schema automatically)
spring.jpa.hibernate.ddl-auto=update

