spring.application.name=fintrackautentication
spring.config.import=optional:file:.env[.properties]

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.flyway.baselineOnMigrate=true

jwt.secret=${JWT_SECRET}

# JWT expirations (milliseconds)
jwt.access.expiration-ms=900000
jwt.refresh.expiration-ms=604800000

security.max-intentos-fallidos=5

server.port=${PORT:8083}